{Jedi Windows Security Code Library Header File
Do not add pasdoc comments into this file!}

//Freepascal compability mode
{.$DEFINE FPC}

//use JEDI Component Library
{.$DEFINE JCL}


{$INCLUDE Compilers.inc}

{$IFDEF FPC}
{$mode delphi}{.$H+}
{$ENDIF}

//the following line must be at the end of this file!!
{Warning: This line is printed because an identifier has no pasdoc comment. This error must be fixed.}
